#ifndef ODOMETRY_PREDEFINED_H
#define ODOMETRY_PREDEFINED_H

#define REPROJECTION_ERROR_3D_THRESHOLD 0.01
#define REPROJECTION_ERROR_2D_THRESHOLD 6

#define LAMBDA_HYBRID_DEPTH 0.5
#define MAX_DIFF_DEPTH 0.05
#define SOBEL_SCALE 0.125
#define MAX_DEPTH 4
#define MIN_DEPTH 0.5

#define MAX_INLIER_RATIO_DENSE 0.9
#define MIN_INLIER_RATIO_DENSE 0.3

#define MAX_INLIER_RATIO_SPARSE 0.9
#define MIN_INLIER_RATIO_SPARSE 0.2

#define MIN_INLIER_SPARSE 50
#endif